#!/bin/bash
#automatic generated from mmi_pckg.vhd
  export C_MMI_ADDR_MAP_REVISION     = 1 # Address map version
  export C_MMI_DATA_WIDTH           = 32
  export C_MMI_ADDR_WIDTH           = 20  #defines the width of the address bus
  export C_MMI_BASE_ADDR_WIDTH      = 12  #defines the width of the base address part
  export C_MMI_BASE_UPPER           = 19  #defines the MSB of the base address part
  export C_MMI_BASE_LOWER           =  8  #defines the LSB of the base address part
  export C_MMI_SUB_ADDR_WIDTH       =  8  #defines the width of the sub address part
  export C_MMI_SUB_UPPER            =  7  #defines the MSB of the sub address part
  export C_MMI_SUB_LOWER            =  0  #defines the LSB of the sub address part
  export C_MMI_PAGE_WIDTH           =  8 #defines the width of PAGE address part
  export C_BASE_ADDR_TN_COMMON                    = 0x000
  export C_SUB_ADDR_COMMON_TN_MAJOR_REV           = 0x00
  export C_SUB_ADDR_COMMON_TN_MINOR_REV           = 0x04
  export C_SUB_ADDR_COMMON_USER_REV               = 0x08
  export C_SUB_ADDR_COMMON_ADDR_MAP_REV           = 0x0C
  export C_SUB_ADDR_COMMON_FPGA_ID0               = 0x10
  export C_SUB_ADDR_COMMON_FPGA_ID1               = 0x14
  export C_SUB_ADDR_COMMON_EFUSE                  = 0x18
  export C_SUB_ADDR_COMMON_BITGEN_TIME            = 0x20
  export C_SUB_ADDR_COMMON_CONFIG_CHECK           = 0x24
  export C_SUB_ADDR_COMMON_FPGA_TEMP              = 0x28
  export C_SUB_ADDR_COMMON_FPGA_ALARM             = 0x2C
  export C_SUB_ADDR_COMMON_FEATURES_6TREE         = 0x30
  export C_SUB_ADDR_COMMON_FEATURES_ETH_SW        = 0x34
  export C_SUB_ADDR_COMMON_FEATURES_FLOWCACHE     = 0x38
  export C_SUB_ADDR_COMMON_FEATURES_ACC_DP        = 0x3C
  export C_SUB_ADDR_COMMON_FEATURES_SFP           = 0x40
  export C_SUB_ADDR_COMMON_FEATURES_SODIMM        = 0x44
  export C_SUB_ADDR_COMMON_PARAM_PRT_CNT          = 0x50
  export C_SUB_ADDR_COMMON_PARAM_DP_CNT           = 0x54
  export C_SUB_ADDR_COMMON_PARAM_BUF_CNT          = 0x58
  export C_SUB_ADDR_COMMON_PARAM_RX_MIN           = 0x60
  export C_SUB_ADDR_COMMON_PARAM_RX_MAX           = 0x64
  export C_SUB_ADDR_COMMON_PARAM_TX_PRE           = 0x68
  export C_SUB_ADDR_COMMON_PARAM_TX_IFG           = 0x6C
  export C_SUB_ADDR_COMMON_WIDTH_HC_BAD           = 0x70
  export C_SUB_ADDR_COMMON_WIDTH_ETH_SW           = 0x74
  export C_SUB_ADDR_COMMON_WIDTH_RX_STAT_BAD      = 0x78
  export C_SUB_ADDR_COMMON_FIFO_OVERFLOW0         = 0x80
  export C_SUB_ADDR_COMMON_FIFO_OVERFLOW1         = 0x84
  export C_SUB_ADDR_COMMON_FIFO_UNDERRUN0         = 0x88
  export C_SUB_ADDR_COMMON_FIFO_UNDERRUN1         = 0x8C
  export C_SUB_ADDR_COMMON_PCIE_ERROR0            = 0x90
  export C_SUB_ADDR_COMMON_PCIE_ERROR1            = 0x94
  export C_SUB_ADDR_COMMON_PCIE_TIMEOUT_CNT       = 0x98
  export C_SUB_ADDR_COMMON_BUFFER_FULL            = 0xA0
  export C_SUB_ADDR_COMMON_TXF_FULL               = 0xA4
  export C_BASE_ADDR_MDIO                         = 0x010 # mmi_mdio
  export C_SUB_ADDR_MDIO_WRITE          = 0x00 # Command & Write Data
  export C_SUB_ADDR_MDIO_READ           = 0x04 # Status & Read Data
  export C_SUB_ADDR_RGMII_TAP           = 0x00 # RW
  export C_SUB_ADDR_RGMII_LINK_STAT     = 0x04 # RO
  export C_SUB_ADDR_RGMII_CLK_SPEED     = 0x08 # RO
  export C_SUB_ADDR_RGMII_DPX_STAT      = 0x0C # RO
  export C_SUB_ADDR_DISPLAYMUX_MMI_disp_src    =0x00
  export C_BASE_ADDR_UDISPLAYMUX                         = 0x800 # user_module_mmi
  export C_BASE_ADDR_MAC_0     = 0x030
  export C_BASE_ADDR_MAC_1     = 0x031
  export C_BASE_ADDR_MAC_2     = 0x032
  export C_BASE_ADDR_MAC_3     = 0x033
  export C_BASE_ADDR_MAC_4     = 0x034
  export C_BASE_ADDR_MAC_5     = 0x035
  export C_BASE_ADDR_MAC_6     = 0x036
  export C_BASE_ADDR_MAC_7     = 0x037
  export C_BASE_ADDR_MAC_8     = 0x038
  export C_BASE_ADDR_MAC_9     = 0x039
  export C_BASE_ADDR_MAC_10     = 0x03A
  export C_BASE_ADDR_MAC_11     = 0x03B
  export C_SUB_ADDR_MAC_6T_ADDR_L          = 0x00 # lower 32Bit of 6T Addr
  export C_SUB_ADDR_MAC_6T_ADDR_H          = 0x04 # upper Bits of 6T Addr
  export C_SUB_ADDR_MAC_6T_SRC_PTR         = 0x08 # Index in 6T Addr
  export C_SUB_ADDR_MAC_6T_DST_PTR         = 0x0C # Index in 6T addr
  export C_SUB_ADDR_MAC_OWN_MAC_ADDR_L     = 0x10 # lower 32Bit of our own MAC Address
  export C_SUB_ADDR_MAC_OWN_MAC_ADDR_H     = 0x14 # upper Bits of our own MAC Address
  export C_SUB_ADDR_HC_CNT_BAD_FRAMES     = 0x00
  export C_SUB_ADDR_ETH_SW_COMMON                   = 0x00
  export C_SUB_ADDR_ETH_SW_NUM_SOF                  = 0x10
  export C_SUB_ADDR_ETH_SW_NUM_LEARNED              = 0x14
  export C_SUB_ADDR_ETH_SW_NUM_AGED_OUT             = 0x18
  export C_SUB_ADDR_ETH_SW_NUM_FLOOD_UNKNOWN        = 0x1C
  export C_SUB_ADDR_ETH_SW_NUM_FLOOD_FULL           = 0x20
  export C_SUB_ADDR_ETH_SW_NUM_PORT_ERROR           = 0x24
  export C_SUB_ADDR_ETH_SW_NUM_MATCH_SRC            = 0x28
  export C_SUB_ADDR_ETH_SW_NUM_MATCH_DST            = 0x2C
  export C_SUB_ADDR_ETH_SW_CMP_SRC_MATCH_L          = 0x30
  export C_SUB_ADDR_ETH_SW_CMP_SRC_MATCH_H          = 0x34
  export C_SUB_ADDR_ETH_SW_CMP_DST_MATCH_L          = 0x38
  export C_SUB_ADDR_ETH_SW_CMP_DST_MATCH_H          = 0x3C
  export C_SUB_ADDR_ETH_SW_TABLE_ADDR               = 0x50
  export C_SUB_ADDR_ETH_SW_TABLE_DATA_L             = 0x54
  export C_SUB_ADDR_ETH_SW_TABLE_DATA_H             = 0x58
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_7_0          = 0x60
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_15_8         = 0x64
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_23_16        = 0x68
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_31_24        = 0x6C
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_39_32        = 0x70
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_47_40        = 0x74
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_55_48        = 0x78
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_63_56        = 0x7C
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_71_64        = 0x80
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_79_72        = 0x84
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_87_80        = 0x88
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_95_88        = 0x8C
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_103_96       = 0x90
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_111_104      = 0x94
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_119_112      = 0x98
  export C_SUB_ADDR_ETH_SW_BUCKET_FILL_127_120      = 0x9C
  export C_BASE_ADDR_FLOW_CACHE_HASH_LOWER       = 0x100 #U --flow cache hash table is defined as range  0x10000 to 0x1fffc
  export C_BASE_ADDR_FLOW_CACHE_HASH_UPPER       = 0x1FF #U --flow cache hash table is defined as range  0x10000 to 0x1fffc
  export C_BASE_ADDR_FLOW_CACHE_EMA_CAM          = 0x200
  export C_BASE_ADDR_FLOW_CACHE_FIELD_LOWER      = 0x300 #U --flow cache rules table is defined as range  0x30000 to 0x37ffc
  export C_BASE_ADDR_FLOW_CACHE_FIELD_UPPER      = 0x37F #U --flow cache rules table is defined as range  0x30000 to 0x37ffc
  export C_BASE_ADDR_FLOW_CACHE_LINEAR_LOWER     = 0x500 #U --flow cache linear search is defined as range  0x50000 to 0x501fc
  export C_BASE_ADDR_FLOW_CACHE_LINEAR_UPPER     = 0x501 #U --flow cache linear search is defined as range  0x50000 to 0x501fc
  export C_BASE_ADDR_FLOW_CACHE_EMA_LOWER        = 0x600 #U
  export C_BASE_ADDR_FLOW_CACHE_EMA_UPPER        = 0x61F #U
  export C_BASE_ADDR_USER_MOD                      = 0x700 # user_module_mmi
  export C_SUB_ADDR_USER_MOD_MMI_ID                = 0x00 # RW  Address for "unique" pattern
  export C_SUB_ADDR_USER_MOD_MMI_BEEP_EN           = 0x04 # RW  Address to enable beeping
  export C_SUB_ADDR_USER_MOD_MMI_DISPLAY_EN        = 0x08 # RW  Address to enable display dots
  export C_SUB_ADDR_USER_MOD_MMI_PKT_CNT0          = 0x0C # RO,COR  Address for RX DP0 packet counter
  export C_SUB_ADDR_USER_MOD_MMI_PKT_CNT1          = 0x10 # RO,COR  Address for RX DP1 packet counter
  export C_SUB_ADDR_USER_MOD_MMI_PKT_CNT_WIDE0     = 0x14 # RO  Address for wide RX DP0 packet counter
  export C_SUB_ADDR_USER_MOD_MMI_PKT_CNT_WIDE1     = 0x18 # RO  Address for wide RX DP1 packet counter
  export C_BASE_ADDR_NOC_ACTION_LOWER             = 0x800 #U
  export C_BASE_ADDR_NOC_ACTION_UPPER             = 0x807 #U
  export C_BASE_ADDR_TM                          = 0xA00 # mmi_tm
  export C_SUB_ADDR_TM_QUEUE_THRES_FULL     = 0x00 # lower 32Bit of 6T Addr
  export C_BASE_ADDR_PERIPH                      = 0xC00 # mmi_peripherals
  export C_SUB_ADDR_PERIPH_BUTTONS        = 0x00 # RO  Address for front and back buttons
  export C_SUB_ADDR_PERIPH_INTERRUPTS     = 0x04 # RO  Address for PHY interrupts
  export C_SUB_ADDR_PERIPH_LEDS           = 0x08 # RW  Address for the LEDs
  export C_SUB_ADDR_PERIPH_GPIOS          = 0x0C # RW  Address for the GPIO headers
  export C_SUB_ADDR_PERIPH_DISPLAY0       = 0x10 # RW  Address for the front panel display
  export C_SUB_ADDR_PERIPH_DISPLAY1       = 0x14 # RW  Address for the front panel display
  export C_SUB_ADDR_PERIPH_DISPLAY2       = 0x18 # RW  Address for the front panel display
  export C_SUB_ADDR_PERIPH_DISPLAY3       = 0x1C # RW  Address for the front panel display
  export C_SUB_ADDR_PERIPH_BEEP           = 0x20 # RW  Address for the beeper
  export C_SUB_ADDR_PERIPH_BRIGHTNESS     = 0x24 # RW  Address for the display brightness
