Trustnode Driver: INR-NW.h File Reference
INR-NW.h File Reference
settings and definitions Netork communication
Data Structures
struct INR_NW_packet
struct INR_NW_priv
Macros
#define INR_NWDEV_features NETIF_F_SG | NETIF_F_IP_CSUM | NETIF_F_FRAGLIST
#define INR_NW_devcount 16 /* count of NW-devices */
#define INR_NW_repeatonbusy 0 /* repeat sending packetes to hardware if device is busy */
Functions
void INR_HW_tx (char *buf, int len)
void INR_NW_rx (struct net_device *nwdev, struct INR_NW_packet *pkt)
int INR_NW_config (struct net_device *nwdev, struct ifmap *map)
int INR_NW_open (struct net_device *nwdev)
int INR_NW_stop (struct net_device *nwdev)
netdev_tx_t INR_NW_tx (struct sk_buff *skb, struct net_device *nwdev)
int INR_NW_header (struct sk_buff *skb, struct net_device *nwdev, unsigned short type, const void *daddr, const void *saddr, unsigned len)
int INR_NW_rebuild_header (struct sk_buff *skb)
int INR_NW_ioctl (struct net_device *nwdev, struct ifreq *rq, int cmd)
struct net_device_stats * INR_NW_stats (struct net_device *nwdev)
int INR_NW_change_mtu (struct net_device *nwdev, int new_mtu)
void INR_NW_tx_timeout (struct net_device *nwdev)
int INR_NW_init (struct net_device *nwdev)
struct net_device * get_nwdev (uint8_t index)
void set_nwdev (uint8_t index, struct net_device *dev)
int INR_NW_set_features (struct net_device *net, netdev_features_t features)
Variables
static const struct net_device_ops INR_NW_netdev_ops
net_device definition
static const struct header_ops INR_NW_header_ops
network device header
Detailed Description
settings and definitions Netork communication
Author
M.Ulbricht 2015
Definition in file INR-NW.h.
Function Documentation
struct net_device* get_nwdev (uint8_t index)
return pointer to net-dev
Parameters
index index of NW-device
Definition at line 28 of file INR-NW.c.
Referenced by INR_NAPI_init(), INR_PCI_process_rx_descriptor_ring(), and XPCIe_IRQHandler().
 {
   return globnwdev[index];
 }
int INR_NW_change_mtu (struct net_device * nwdev, int new_mtu)
change mtu
Parameters
cahnge mtu
nwdev network device
Definition at line 314 of file INR-NW.c.
References INR_LOG_debug().
 {
   INR_LOG_debug ("change_mtu called\n");
   return 0;
 }
int INR_NW_config (struct net_device * nwdev, struct ifmap * map)
NW-config
Parameters
nwdev network device
config change-map
Definition at line 82 of file INR-NW.c.
References INR_LOG_debug().
 {
   INR_LOG_debug ("NW-config called\n");
   return 0;
 }
int INR_NW_init (struct net_device * nwdev)
init nw-device structure
Parameters
nwdev network device
Definition at line 340 of file INR-NW.c.
References INR_LOG_debug(), and INR_NW_netdev_ops.
Referenced by INR_NWDEV_init().
 {
   struct INR_NW_priv *priv = netdev_priv (nwdev);
   //globnwdev=&nwdev;
   memset (priv, 0, sizeof (struct INR_NW_priv));
   spin_lock_init (&priv->lock);
   priv->dev = nwdev;
   priv->port = nwdev_counter++; //get device index from name q&d ;)
   nwdev->netdev_ops = &INR_NW_netdev_ops;
   nwdev->features |= INR_NWDEV_features;
   //nwdev->features|=NETIF_F_FRAGLIST;
   //nwdev->header_ops = &INR_NW_header_ops;
   //nwdev->flags |= NETIF_F_HIGHDMA;    //place mor flags here
   //INR_NW->hw_features|=NETIF_F_SG;
   //INR_NW->hw_features|=NETIF_F_FRAGLIST;
   nwdev->hw_features |= nwdev->features;
   ether_setup (nwdev);
   /*nwdev->open = INR_NW_open;
      nwdev->stop = INR_NW_stop;
      nwdev->hard_start_xmit = INR_NW_xmit; */
   INR_LOG_debug ("Init NWDev %i done\n", priv->port);
   return 0;
 }
int INR_NW_ioctl (struct net_device * nwdev, struct ifreq * rq, int cmd)
change device options
Parameters
nwdev network device
rq
cmd
Definition at line 287 of file INR-NW.c.
 {
   //INR_LOG_debug ("ioctl called\n");
   return 0;
 }
int INR_NW_open (struct net_device * nwdev)
NW-dev open
Parameters
nwdev network device
Definition at line 96 of file INR-NW.c.
References INR_LOG_debug().
 {
   INR_LOG_debug ("NWDev open\n");
   memcpy (nwdev->dev_addr, "\0SNUL1", ETH_ALEN);
   memcpy (nwdev->broadcast, "\0\0\0\0\0\0", ETH_ALEN);
   struct INR_NW_priv *priv = netdev_priv (nwdev);
   nwdev->dev_addr[ETH_ALEN - 1] = priv->port;
 //nwdev->mtu=900;
   uint8_t i = 0;
   for (i = 0; i < ETH_ALEN; i++)
     nwdev->broadcast[i] = (uint8_t) 0xff;
   INR_LOG_debug ("HW-addr:%x Broadcast-addr:%x\n", nwdev->dev_addr, nwdev->broadcast);
   netif_start_queue (nwdev);
   return 0;
 }
void INR_NW_rx (struct net_device * nwdev, struct INR_NW_packet * pkt)
NW-rx
Parameters
nwdev
pkt Ethernetpacket
Definition at line 53 of file INR-NW.c.
References INR_LOG_debug().
 {
   INR_LOG_debug ("rx called\n");
   struct sk_buff *skb;
   struct INR_NW_priv *priv = netdev_priv (nwdev);
   skb = dev_alloc_skb (pkt->datalen + 2);
   if (!skb) {
     priv->stats.rx_dropped++;
     return;
   }
   skb_reserve (skb, 2);
   memcpy (skb_put (skb, pkt->datalen), pkt->data, pkt->datalen);
   skb->dev = nwdev;
   skb->protocol = eth_type_trans (skb, nwdev);
   skb->ip_summed = CHECKSUM_UNNECESSARY;
   priv->stats.rx_packets++;
   priv->stats.rx_bytes += pkt->datalen;
   netif_rx (skb);
   return;
 }
struct net_device_stats* INR_NW_stats (struct net_device * nwdev)
return device statistics
Parameters
nwdev network device
Definition at line 301 of file INR-NW.c.
 {
   struct INR_NW_priv *priv = netdev_priv (nwdev);
   return &priv->stats;
 }
int INR_NW_stop (struct net_device * nwdev)
NW-dev stop
Parameters
nwdev network device
Definition at line 119 of file INR-NW.c.
References INR_LOG_debug().
 {
   INR_LOG_debug ("NWDev stop\n");
   netif_stop_queue (nwdev);
 }
netdev_tx_t INR_NW_tx (struct sk_buff * skb, struct net_device * nwdev)
Software transmit function, called by kernel
Parameters
skb socket buffer
nwdev network device
skb_data
Definition at line 133 of file INR-NW.c.
References INR_LOG_debug(), INR_STATUS_get(), and INR_TX_push().
 {
   if (INR_STATUS_get (INR_STATUS_HW_RUNNING)) {
     struct INR_NW_priv *priv = netdev_priv (nwdev);
 //if(skb_shinfo(skb)->nr_frags)INR_LOG_debug("TX fragmented Packet ;)\n");
 //INR_LOG_debug("TX frags:%i datalen:%i len:%i\n",skb_shinfo(skb)->nr_frags,skb->data_len,skb->len);
     uint8_t toport = priv->port;
 //    if (priv->port == 0)      //q&d crossbar for testing with chrinstans magic
 //      toport = 0;
 //    if (priv->port == 1)      toport = 0b1000;
     uint8_t error = 0;
     unsigned int from;
     unsigned int to = skb->len;
     struct skb_seq_state st;
     const u8 *data;
     unsigned int len;
     unsigned int consumed = 0;
     from = 0;
     if (skb_shinfo (skb)->nr_frags) {
       if (zerocopy_tx) {
 //INR_LOG_debug("TX zerocopy %i frags\n",skb_shinfo (skb)->nr_frags);
     int i = 0;
     error = INR_TX_push (skb, skb->data, skb_headlen (skb), 0, toport, 0, 1, skb_shinfo (skb)->nr_frags);   //push skb-data
     if (error)
       goto errorhandling;
     for (i = 0; i < skb_shinfo (skb)->nr_frags - 1; i++) {
       error = INR_TX_push (skb, page_address (skb_shinfo (skb)->frags[i].page.p) + skb_shinfo (skb)->frags[i].page_offset, skb_shinfo (skb)->frags[i].size, 0, toport, 0, 1, skb_shinfo (skb)->nr_frags - i);   //add fragments
       if (error)
         goto errorhandling;
     }
     i = skb_shinfo (skb)->nr_frags - 1;
     error = INR_TX_push (skb, page_address (skb_shinfo (skb)->frags[i].page.p) + skb_shinfo (skb)->frags[i].page_offset, skb_shinfo (skb)->frags[i].size, 1, toport, 0, 1, 1);  //add last fragment
     if (error)
       goto errorhandling;
       }
       else {
 //INR_LOG_debug("TX seq-read %i frags\n",skb_shinfo (skb)->nr_frags);
     skb_prepare_seq_read (skb, from, to, &st);
     while ((len = skb_seq_read (consumed, &data, &st)) != 0) {
       if (consumed + len == to)
         error = INR_TX_push (skb, data, len, 1, toport, 0, 0, 1);
       if (error)
         goto errorhandling;
       else
         error = INR_TX_push (skb, data, len, 0, toport, 0, 0, 30);  //assume that you need 30 fragments free space
       if (error)
         goto errorhandling;
       consumed += len;
     }
       }
     }
     else {
 //INR_LOG_debug("TX copy to nonfragmented\n");
       if (skb->len > INR_PCI_FPGA_max_tx_length) {
     uint16_t rest = skb->len;
     uint16_t offset = 0, nextfrag = 0;
     uint8_t last = 0;
     uint64_t countfrag = 0;
     while (rest) {
       if (rest > INR_PCI_FPGA_max_tx_length) {
         nextfrag = INR_PCI_FPGA_max_tx_length;
       }
       else {
         nextfrag = rest;
         last = 1;
       }
       uint8_t *skb_data = kmalloc (nextfrag, GFP_DMA | GFP_ATOMIC);
       if (!skb_data)
         INR_LOG_debug ("Cant alloc tx data\n");
       else {
         memcpy (skb_data, skb->data + offset, nextfrag);
         error = INR_TX_push (skb, skb_data, nextfrag, last, toport, 1, 0, (skb->len / INR_PCI_FPGA_max_tx_length) + 1 - countfrag);
         countfrag++;
         if (error)
           goto errorhandling;   //free mem if pkt is dropped
       }
       offset += nextfrag;
       rest -= nextfrag;
     }
       }
       else {
     uint8_t *skb_data;  //= kmalloc (skb->len, GFP_DMA|GFP_ATOMIC);
 //      uint8_t *skb_tmp;
     if (0)
       INR_LOG_debug ("Cant alloc tx data\n");
     else {
       //memcpy (skb_data, skb->data, skb->len);
       skb_data = kmemdup (skb->data, skb->len, GFP_DMA);
       if (!skb_data) {
         INR_LOG_debug ("Cant alloc tx data\n");
         goto errorhandling;
       }
 /*uint32_t h=0;
 skb_tmp=skb;
 for (h=0;h<skb->len;h++) skb_data[h]= (uint8_t)skb_tmp[h];*/
       error = INR_TX_push (skb, skb_data, skb->len, 1, toport, 1, 0, 1);
       if (error) {
         if (skb_data)
           kfree (skb_data);
         goto errorhandling; //free mem if pkt is dropped
       }
     }
       }
     }
 /*uint8_t tmpdata[testdate_size];
 uint16_t i;
 for (i=0;i<testdate_size;i++)tmpdata[i]=i&0xff;
 INR_TX_push (skb,tmpdata, testdate_size, 1, toport, 1);
 */
     //dev_kfree_skb (skb);
     priv->stats.tx_packets++;
     priv->stats.tx_bytes += skb->len;
   errorhandling:
     if (error) {
       priv->stats.tx_dropped++; //fpga descriptorrin full pkt dropped
       if (INR_NW_repeatonbusy) {
     return NETDEV_TX_BUSY;  //dont drop, just tell nw stack to repeat
       }
       else {
 // if not repeat just drop, nw stack will not realize
     if (skb)
       kfree_skb (skb);  //free skb if dropped (handled by nw_stack if returned busy)
     return NETDEV_TX_OK;
       }
     }
     return NETDEV_TX_OK;
   }
   return NETDEV_TX_BUSY;
 }
void INR_NW_tx_timeout (struct net_device * nwdev)
tx-timeut function
Parameters
nwdev network device
Definition at line 326 of file INR-NW.c.
References INR_LOG_debug().
 {
   INR_LOG_debug ("tx_timeour called\n");
   return;
 }
void set_nwdev (uint8_t index, struct net_device * dev)
store net-dev point for later use
Parameters
index index of NW-device
dev NW-dev
Definition at line 39 of file INR-NW.c.
References INR_NW_STATUS_set().
Referenced by INR_NWDEV_init().
 {
   globnwdev[index] = dev;
   INR_NW_STATUS_set (1 << index);
 }               //
Variable Documentation
const struct header_ops INR_NW_header_ops static
Initial value:
= {
  .create = INR_NW_header,
  .cache = NULL,
}
network device header
Definition at line 57 of file INR-NW.h.
const struct net_device_ops INR_NW_netdev_ops static
Initial value:
= {
  .ndo_open = INR_NW_open,
  .ndo_stop = INR_NW_stop,
  .ndo_set_config = INR_NW_config,
  .ndo_start_xmit = INR_NW_tx,
  .ndo_get_stats = INR_NW_stats,
  .ndo_change_mtu = INR_NW_change_mtu,
  .ndo_tx_timeout = INR_NW_tx_timeout,
  .ndo_set_features = INR_NW_set_features,
}
net_device definition
Definition at line 41 of file INR-NW.h.
Referenced by INR_NW_init().