Trustnode Driver: INR-ctl.c File Reference
INR-ctl.c File Reference
Functions for Proc-filesystem.
#include <linux/kernel.h>
#include <linux/export.h>
#include <linux/module.h>
#include <linux/pci.h>
#include <linux/init.h>
#include <linux/interrupt.h>
#include <linux/delay.h>
#include <linux/netdevice.h>
#include <linux/etherdevice.h>
#include <linux/proc_fs.h>
#include <linux/openvswitch.h>
#include <linux/kthread.h>
#include <asm/signal.h>
#include <linux/semaphore.h>
#include "INR.h"
#include "INR-PCI.h"
#include "INR-ctl.h"
Macros
#define PROCFS_MAX_SIZE 1024
Functions
int procfile_write (struct file *file, const char *buffer, unsigned long count, void *data)
int procfile_write2 (struct file *file, const char *buffer, unsigned long count, void *data)
static int hello_proc_show (struct seq_file *m, void *v)
static int hello_proc_open (struct inode *inode, struct file *file)
static int hello_proc_show2 (struct seq_file *m, void *v)
static int hello_proc_open2 (struct inode *inode, struct file *file)
int INR_CTL_init_proc (struct pci_dev *dev)
dev PCI-device
int INR_CTL_remove_proc (struct pci_dev *dev)
dev PCI-device
void INR_CTL_init_ovs ()
void INR_CTL_ovs_d (void *nix)
void INR_CTL_ovs_flow_add ()
void INR_CTL_ovs_flow_rm ()
void INR_CTL_ovs_flow_flush ()
Variables
static char procfs_buffer [1024]
static unsigned long procfs_buffer_size = 0
static struct proc_dir_entry * reg1
static struct proc_dir_entry * reg2
static struct proc_dir_entry * INR_proc_dir
uint8_t globalvar
void * gBaseVirt1 = NULL
unsigned long gBaseHdwr1
unsigned long gBaseLen1
Detailed Description
Functions for Proc-filesystem.
Author
M.Ulbricht 2015
Definition in file INR-ctl.c.
Function Documentation
void INR_CTL_init_ovs (void)
Init connection to openvswitch
Definition at line 240 of file INR-ctl.c.
Referenced by probe().
 {
   //kthread_run (&INR_CTL_ovs_d, NULL, "INR_ovs_d");
 }
int INR_CTL_init_proc (struct pci_dev * dev)
dev PCI-device
Init function for proc-fs
Definition at line 123 of file INR-ctl.c.
References gBaseHdwr1, gBaseLen1, gBaseVirt1, and INR_LOG_debug().
Referenced by probe().
 {
   gBaseHdwr1 = pci_resource_start (dev, 1);
   // Print Base Address to kernel log
   INR_LOG_debug ("Init: Base hw1 val %x\n", (unsigned int) gBaseHdwr1);
   // Get the Base Address Length
   gBaseLen1 = pci_resource_len (dev, 1);
   // Print the Base Address Length to Kernel Log
   INR_LOG_debug ("Init: Base hw len %i\n", (unsigned int) gBaseLen1);
   gBaseVirt1 = pci_iomap (dev, 1, 0);
   //gBaseVirt = ioremap (gBaseHdwr, gBaseLen);  //prepare bar0 for access
   INR_LOG_debug ("Init: Bar1 mapped\n");
   if (!gBaseVirt1) {
     INR_LOG_debug ("Init: Could not remap memory.\n");
     return (1);
   }
 /*nor more available in kernel 4.x
   if (0 > check_mem_region (gBaseHdwr1, REGISTER_SIZE)) //check if wee con access bar0
   {
     INR_LOG_debug ("Init: Memory in use.\n");
     return (1);
   }
 */
   INR_LOG_debug ("Init: mem region checked\n");
 /*INR_proc_dir=proc_mkdir("trustnode", NULL);
         if (!INR_proc_dir)
                 return;
 */
   //INR_PCI_BAR1_write (1234, 0x4);
   //INR_PCI_BAR1_write (5678, 0x0);
   //INR_LOG_debug ("rwtest:%i", INR_PCI_BAR1_read (0x0));
   //INR_LOG_debug ("rwtest:%i", INR_PCI_BAR1_read (0x4));
   static const struct file_operations hello_proc_fops = {
     .owner = THIS_MODULE,
     .open = hello_proc_open,
     .write = procfile_write,
     .read = seq_read,
     .llseek = seq_lseek,
     .release = single_release,
   };
   reg1 = proc_create ("trustnode1", 0644, NULL, &hello_proc_fops);
   if (reg1 == NULL) {
     remove_proc_entry ("trustnode1", NULL);
     printk (KERN_ALERT "Error: Could not initialize /proc/%s\n", "trustnode1");
     return -ENOMEM;
   }
 /*
     reg1->read_proc = procfile_read;
     reg1->owner      = THIS_MODULE;
     reg1->mode   = S_IFREG | S_IRUGO;
     reg1->uid    = 0;
     reg1->gid    = 0;
     reg1->size   = 37;
 */
   printk (KERN_INFO "/proc/%s created\n", "Trustnode");
   static const struct file_operations hello_proc_fops2 = {
     .owner = THIS_MODULE,
     .open = hello_proc_open2,
     .write = procfile_write2,
     .read = seq_read,
     .llseek = seq_lseek,
     .release = single_release,
   };
   reg2 = proc_create ("trustnode2", 0644, NULL, &hello_proc_fops2);
   if (reg2 == NULL) {
     remove_proc_entry ("trustnode2", NULL);
     printk (KERN_ALERT "Error: Could not initialize /proc/%s\n", "trustnode2");
     return -ENOMEM;
   }
 /*
     reg2->read_proc = procfile_read2;
     reg2->owner      = THIS_MODULE;
     reg2->mode   = S_IFREG | S_IRUGO;
     reg2->uid    = 0;
     reg2->gid    = 0;
     reg2->size   = 37;
 */
   printk (KERN_INFO "/proc/%s created\n", "Trustnode2");
   return 0;         /* everything is ok */
 }
void INR_CTL_ovs_d (void * nix)
ovs link deamon
Definition at line 254 of file INR-ctl.c.
 {
   /*allow_signal (SIGKILL);
      while (1) {
      if (signal_pending (current))
      break;
      //down(&INR_TN_ovscon_sema);
      if (INR_TN_ovscon_comand) {
      switch (INR_TN_ovscon_comand) {
      case INR_TN_ovsctl_cmd_ADD:
      INR_CTL_ovs_flow_add ();
      break;
      case INR_TN_ovsctl_cmd_RM:
      INR_CTL_ovs_flow_rm ();
      break;
      case INR_TN_ovsctl_cmd_FLUSH:
      INR_CTL_ovs_flow_flush ();
      break;
      default:
      break;
      }
      INR_TN_ovscon_comand = 0;
      }
      //up(&INR_TN_ovscon_sema);
      msleep (100);
      } */
 }
void INR_CTL_ovs_flow_add (void)
new flow in ovs table
Definition at line 289 of file INR-ctl.c.
References INR_LOG_debug().
 {
   INR_LOG_debug ("add new flow\n");
 }
void INR_CTL_ovs_flow_flush (void)
flush ovs table
Definition at line 311 of file INR-ctl.c.
References INR_LOG_debug().
 {
   INR_LOG_debug ("flosh table\n");
 }
void INR_CTL_ovs_flow_rm (void)
remove flow in ovs table
Definition at line 300 of file INR-ctl.c.
References INR_LOG_debug().
 {
   INR_LOG_debug ("rm flow\n");
 }
int INR_CTL_remove_proc (struct pci_dev * dev)
dev PCI-device
Remove function for proc-fs
Definition at line 221 of file INR-ctl.c.
Referenced by remove().
 {
   remove_proc_entry ("trustnode1", NULL);
   printk (KERN_INFO "/proc/%s removed\n", "trustnode1");
   remove_proc_entry ("trustnode2", NULL);
   printk (KERN_INFO "/proc/%s removed\n", "trustnode2");
 //remove_proc_entry("trustnode", NULL);
 }
Variable Documentation
unsigned long gBaseHdwr1
start-address of bar0
Definition at line 40 of file INR-ctl.c.
Referenced by INR_CTL_init_proc().
unsigned long gBaseLen1
legth of bar0
Definition at line 40 of file INR-ctl.c.
Referenced by INR_CTL_init_proc().
void* gBaseVirt1 = NULL
pointer for start-address of bar0
Definition at line 39 of file INR-ctl.c.
Referenced by INR_CTL_init_proc().
uint8_t globalvar
comment for globalvar
Definition at line 38 of file INR-ctl.c.
unsigned long procfs_buffer_size = 0 static
<Command from ovs datapath The size of the buffer
Definition at line 36 of file INR-ctl.c.