Trustnode Driver: INR.c File Reference
INR.c File Reference
Global helper functions.
#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/pci.h>
#include <linux/init.h>
#include <linux/interrupt.h>
#include <linux/delay.h>
#include <linux/netdevice.h>
#include <linux/etherdevice.h>
#include "INR.h"
Functions
void INR_CHECK_fpga_read_val (uint64_t val, const char *msg, uint8_t bit64)
void INR_NW_STATUS_set (uint64_t stat)
uint8_t INR_NW_STATUS_get (uint64_t stat)
void INR_STATUS_set (uint64_t stat)
uint8_t INR_STATUS_get (uint64_t stat)
void INR_LOG_timelog_init ()
void INR_LOG_debug (const char *strg,...)
void INR_LOG_timelog (const char *strg,...)
Variables
const uint8_t debug_enable = 1
const uint8_t fpga_read_check = 1
const uint8_t timelog_enable = 1
struct timespec INR_LOG_lasttime
volatile uint64_t INR_status = 0
volatile uint64_t INR_NW_status = 0
Detailed Description
Global helper functions.
Author
M.Ulbricht 2015
Definition in file INR.c.
Function Documentation
void INR_CHECK_fpga_read_val (uint64_t val, const char * msg, uint8_t bit64)
error if 0xffffffffffffffff is readed from fpga
Parameters
val value to check
Definition at line 27 of file INR.c.
References INR_LOG_debug().
Referenced by INR_PCI_process_rx_descriptor_ring(), and INR_TX_unmap_d().
 {
   if (fpga_read_check) {
     if (bit64)
       if (val == 0xffffffffffffffff)
     INR_LOG_debug ("FPGA read check faild: %s", msg);
       else if (val == 0xffffffff)
     INR_LOG_debug ("FPGA read check faild: %s", msg);
   }
 }
void INR_LOG_debug (const char * strg, ...)
central debug print
Parameters
strg message
Definition at line 103 of file INR.c.
Referenced by INR_CHECK_fpga_read_val(), INR_CTL_init_proc(), INR_CTL_ovs_flow_add(), INR_CTL_ovs_flow_flush(), INR_CTL_ovs_flow_rm(), INR_init_drv(), INR_int_enable(), INR_NAPI_init(), INR_NW_change_mtu(), INR_NW_config(), INR_NW_init(), INR_NW_open(), INR_NW_rx(), INR_NW_stop(), INR_NW_tx(), INR_NW_tx_timeout(), INR_NWDEV_destroi(), INR_NWDEV_init(), INR_PCI_get_new_rx_descriptor_ring_entry(), INR_PCI_process_rx_descriptor_ring(), INR_PCI_rx_descriptor_pool_refill(), INR_PCI_rx_pageallocator(), INR_PCI_tx_unmapper(), INR_PRINT_DESC_status(), INR_PROBE_dma(), INR_remove_drv(), INR_RX_RING_init(), INR_TX_push(), INR_TX_RING_init(), INR_TX_unmap_d(), INR_UNMAP_all(), print_pci_version(), probe(), and remove().
 {
   va_list format;
   va_start (format, strg);  //read following args
   if (debug_enable) {
     printk ("INR:");
     vprintk (strg, format);
     //printk ("\n");
   }
 }
void INR_LOG_timelog (const char * strg, ...)
central timelog print
Parameters
strg message
Definition at line 120 of file INR.c.
 {
   va_list format;
   va_start (format, strg);  //read following args
   if (timelog_enable) {
     struct timespec tmp;
     getnstimeofday (&tmp);
     printk ("INR_Time[%lds%ldns]Diff:[%lds,%ldns]:", tmp.tv_sec,
         tmp.tv_nsec, tmp.tv_sec - INR_LOG_lasttime.tv_sec, tmp.tv_nsec - INR_LOG_lasttime.tv_nsec);
     INR_LOG_lasttime = tmp;
     vprintk (strg, format);
     //printk ("\n");
   }
 }
uint8_t INR_NW_STATUS_get (uint64_t stat)
NW status management
Parameters
stat Status to set
Definition at line 57 of file INR.c.
 {
   if (INR_NW_status & stat)
     return 1;
   else
     return 0;
 }
void INR_NW_STATUS_set (uint64_t stat)
NW status management
Parameters
stat Status to set
Definition at line 46 of file INR.c.
Referenced by set_nwdev().
 {
   INR_NW_status |= stat;
 }
uint8_t INR_STATUS_get (uint64_t stat)
status management
Parameters
stat Status to set
Definition at line 83 of file INR.c.
Referenced by INR_NW_tx(), INR_remove_drv(), and INR_TX_push().
 {
   if (INR_status & stat)
     return 1;
   else
     return 0;
 }
void INR_STATUS_set (uint64_t stat)
status management
Parameters
stat Status to set
Definition at line 72 of file INR.c.
Referenced by INR_init_drv(), INR_int_enable(), INR_RX_RING_init(), INR_TX_RING_init(), and probe().
 {
   INR_status |= stat;
 }