Trustnode Driver: INR-NAPI.h File Reference
INR-NAPI.h File Reference
settings and definitions NAPI
Macros
#define NAPI_enable 1 /*enable new Network API */
#define INR_NAPI_maxpoll 128/*NAPI maxpoll value*/
Functions
void INR_NAPI_init (uint8_t index)
void INR_NAPI_remove (uint8_t index)
void INR_NAPI_schedule (uint8_t index)
void INR_NAPI_complete (uint8_t index)
int INR_NAPI_poll_0 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_1 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_2 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_3 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_4 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_5 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_6 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_7 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_8 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_9 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_10 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_11 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_12 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_13 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_14 (struct napi_struct *napi, int budget)
int INR_NAPI_poll_15 (struct napi_struct *napi, int budget)
Detailed Description
settings and definitions NAPI
Author
M.Ulbricht 2015
Definition in file INR-NAPI.h.
Function Documentation
void INR_NAPI_complete (uint8_t index)
disable NAPI sceduling for sec netdev
Parameters
index index of netdev/RX_descriptorring
Definition at line 125 of file INR-NAPI.c.
Referenced by INR_NAPI_poll_0(), INR_NAPI_poll_1(), INR_NAPI_poll_10(), INR_NAPI_poll_11(), INR_NAPI_poll_12(), INR_NAPI_poll_13(), INR_NAPI_poll_14(), INR_NAPI_poll_15(), INR_NAPI_poll_2(), INR_NAPI_poll_3(), INR_NAPI_poll_4(), INR_NAPI_poll_5(), INR_NAPI_poll_6(), INR_NAPI_poll_7(), INR_NAPI_poll_8(), and INR_NAPI_poll_9().
 {
   napi_complete (&INR_NAPI_rx[index]);  //enable NAPI poll
   //INR_LOG_debug ("Disable NAPI polling for Ring %i\n", index);
 }
void INR_NAPI_init (uint8_t index)
init NAPI for specal netdev device
Parameters
index index of netdev/RX_descriptorring
Definition at line 31 of file INR-NAPI.c.
References get_nwdev(), INR_LOG_debug(), INR_NAPI_poll_0(), INR_NAPI_poll_1(), INR_NAPI_poll_10(), INR_NAPI_poll_11(), INR_NAPI_poll_12(), INR_NAPI_poll_13(), INR_NAPI_poll_14(), INR_NAPI_poll_15(), INR_NAPI_poll_2(), INR_NAPI_poll_3(), INR_NAPI_poll_4(), INR_NAPI_poll_5(), INR_NAPI_poll_6(), INR_NAPI_poll_7(), INR_NAPI_poll_8(), and INR_NAPI_poll_9().
Referenced by INR_init_drv().
 {
   INR_LOG_debug ("Init NAPI for ring %i\n", index);
   switch (index) {
   case 0:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_0, INR_NAPI_maxpoll);
     break;
   case 1:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_1, INR_NAPI_maxpoll);
     break;
   case 2:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_2, INR_NAPI_maxpoll);
     break;
   case 3:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_3, INR_NAPI_maxpoll);
     break;
   case 4:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_4, INR_NAPI_maxpoll);
     break;
   case 5:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_5, INR_NAPI_maxpoll);
     break;
   case 6:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_6, INR_NAPI_maxpoll);
     break;
   case 7:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_7, INR_NAPI_maxpoll);
     break;
   case 8:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_8, INR_NAPI_maxpoll);
     break;
   case 9:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_9, INR_NAPI_maxpoll);
     break;
   case 10:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_10, INR_NAPI_maxpoll);
     break;
   case 11:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_11, INR_NAPI_maxpoll);
     break;
   case 12:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_12, INR_NAPI_maxpoll);
     break;
   case 13:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_13, INR_NAPI_maxpoll);
     break;
   case 14:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_14, INR_NAPI_maxpoll);
     break;
   case 15:
     netif_napi_add (get_nwdev (index), &INR_NAPI_rx[index], INR_NAPI_poll_15, INR_NAPI_maxpoll);
     break;
   default:
     break;
   }
   napi_enable (&INR_NAPI_rx[index]);
 }
int INR_NAPI_poll_0 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 140 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (0);    //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (0);  // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_1 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 155 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (1);    //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (1);  // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_10 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 290 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (10);   //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (10); // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_11 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 305 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (11);   //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (11); // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_12 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 320 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (12);   //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (12); // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_13 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 335 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (13);   //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (13); // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_14 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 350 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (14);   //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (14); // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_15 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 365 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (15);   //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (15); // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_2 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 170 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (2);    //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (2);  // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_3 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 185 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (3);    //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (3);  // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_4 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 200 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (4);    //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (4);  // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_5 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 215 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (5);    //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (5);  // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_6 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 230 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (6);    //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (6);  // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_7 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 245 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (7);    //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (7);  // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_8 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 260 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (8);    //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (8);  // if less packets then budget, disable polling
   return ret;
 }
int INR_NAPI_poll_9 (struct napi_struct * napi, int budget)
NAPI poll fkt for ring 0
Parameters
*napi NAPI
budget how much to poll max
Definition at line 275 of file INR-NAPI.c.
References INR_NAPI_complete(), and INR_PCI_process_rx_descriptor_ring().
Referenced by INR_NAPI_init().
 {
   uint16_t ret = INR_PCI_process_rx_descriptor_ring (9);    //poll paketes form descriptor ring
   if (ret < budget)
     INR_NAPI_complete (9);  // if less packets then budget, disable polling
   return ret;
 }
void INR_NAPI_remove (uint8_t index)
deinit NAPI for specal netdev device
Parameters
index index of netdev/RX_descriptorring
Definition at line 100 of file INR-NAPI.c.
 {
   netif_napi_del (&INR_NAPI_rx[index]);
 }
void INR_NAPI_schedule (uint8_t index)
enable NAPI sceduling for sec netdev
Parameters
index index of netdev/RX_descriptorring
Definition at line 111 of file INR-NAPI.c.
Referenced by XPCIe_IRQHandler().
 {
   napi_schedule (&INR_NAPI_rx[index]);  //enable NAPI poll
   //INR_LOG_debug ("Enable NAPI polling for Ring %i\n", index);
 }