Trustnode Driver: INR.h File Reference
INR.h File Reference
basic settings and definitions
Macros
#define REGISTER_SIZE 30000
#define INR_STATUS_BUSMASTER 1
#define INR_STATUS_BAR0 2
#define INR_STATUS_TX_RING 4
#define INR_STATUS_MSI 8
#define INR_STATUS_INT1 16
#define INR_STATUS_DEVICE 32
#define INR_STATUS_NW_enabled 64
#define INR_STATUS_RX_RING 128
#define INR_STATUS_HW_RUNNING 256
#define INR_STATUS_DRV_INIT_done 512
#define MSI0_IRQ_STATUS 0x104
#define IRQ_EOI 0x50
Functions
void INR_LOG_debug (const char *strg,...)
void INR_LOG_timelog (const char *strg,...)
void INR_LOG_timelog_init (void)
void INR_STATUS_set (uint64_t stat)
void INR_CHECK_fpga_read_val (uint64_t val, const char *msg, uint8_t bit64)
uint8_t INR_STATUS_get (uint64_t stat)
void INR_NW_STATUS_set (uint64_t stat)
uint8_t INR_NW_STATUS_get (uint64_t stat)
Detailed Description
basic settings and definitions
Author
M.Ulbricht 2015
Definition in file INR.h.
Function Documentation
void INR_CHECK_fpga_read_val (uint64_t val, const char * msg, uint8_t bit64)
error if 0xffffffffffffffff is readed from fpga
Parameters
val value to check
Definition at line 27 of file INR.c.
References INR_LOG_debug().
Referenced by INR_PCI_process_rx_descriptor_ring(), and INR_TX_unmap_d().
 {
   if (fpga_read_check) {
     if (bit64)
       if (val == 0xffffffffffffffff)
     INR_LOG_debug ("FPGA read check faild: %s", msg);
       else if (val == 0xffffffff)
     INR_LOG_debug ("FPGA read check faild: %s", msg);
   }
 }
void INR_LOG_debug (const char * strg, ...)
central debug print
Parameters
strg message
Definition at line 103 of file INR.c.
Referenced by INR_CHECK_fpga_read_val(), INR_CTL_init_proc(), INR_CTL_ovs_flow_add(), INR_CTL_ovs_flow_flush(), INR_CTL_ovs_flow_rm(), INR_init_drv(), INR_int_enable(), INR_NAPI_init(), INR_NW_change_mtu(), INR_NW_config(), INR_NW_init(), INR_NW_open(), INR_NW_rx(), INR_NW_stop(), INR_NW_tx(), INR_NW_tx_timeout(), INR_NWDEV_destroi(), INR_NWDEV_init(), INR_PCI_get_new_rx_descriptor_ring_entry(), INR_PCI_process_rx_descriptor_ring(), INR_PCI_rx_descriptor_pool_refill(), INR_PCI_rx_pageallocator(), INR_PCI_tx_unmapper(), INR_PRINT_DESC_status(), INR_PROBE_dma(), INR_remove_drv(), INR_RX_RING_init(), INR_TX_push(), INR_TX_RING_init(), INR_TX_unmap_d(), INR_UNMAP_all(), print_pci_version(), probe(), and remove().
 {
   va_list format;
   va_start (format, strg);  //read following args
   if (debug_enable) {
     printk ("INR:");
     vprintk (strg, format);
     //printk ("\n");
   }
 }
void INR_LOG_timelog (const char * strg, ...)
central timelog print
Parameters
strg message
Definition at line 120 of file INR.c.
 {
   va_list format;
   va_start (format, strg);  //read following args
   if (timelog_enable) {
     struct timespec tmp;
     getnstimeofday (&tmp);
     printk ("INR_Time[%lds%ldns]Diff:[%lds,%ldns]:", tmp.tv_sec,
         tmp.tv_nsec, tmp.tv_sec - INR_LOG_lasttime.tv_sec, tmp.tv_nsec - INR_LOG_lasttime.tv_nsec);
     INR_LOG_lasttime = tmp;
     vprintk (strg, format);
     //printk ("\n");
   }
 }
uint8_t INR_NW_STATUS_get (uint64_t stat)
NW status management
Parameters
stat Status to set
Definition at line 57 of file INR.c.
 {
   if (INR_NW_status & stat)
     return 1;
   else
     return 0;
 }
void INR_NW_STATUS_set (uint64_t stat)
NW status management
Parameters
stat Status to set
Definition at line 46 of file INR.c.
Referenced by set_nwdev().
 {
   INR_NW_status |= stat;
 }
uint8_t INR_STATUS_get (uint64_t stat)
status management
Parameters
stat Status to set
Definition at line 83 of file INR.c.
Referenced by INR_NW_tx(), INR_remove_drv(), and INR_TX_push().
 {
   if (INR_status & stat)
     return 1;
   else
     return 0;
 }
void INR_STATUS_set (uint64_t stat)
status management
Parameters
stat Status to set
Definition at line 72 of file INR.c.
Referenced by INR_init_drv(), INR_int_enable(), INR_RX_RING_init(), INR_TX_RING_init(), and probe().
 {
   INR_status |= stat;
 }