Trustnode Driver: main.c File Reference
main.c File Reference
main driver Function M.Ulbricht 2015
#include <linux/kernel.h>
#include <linux/export.h>
#include <linux/module.h>
#include <linux/pci.h>
#include <linux/init.h>
#include <linux/interrupt.h>
#include <linux/delay.h>
#include <linux/netdevice.h>
#include <linux/etherdevice.h>
#include "INR.h"
#include "INR-PCI.h"
#include "INR-NW.h"
#include "INR-ctl.h"
Functions
int INR_NWDEV_init (void)
init nw-device
void INR_NWDEV_destroi (void)
static int probe (struct pci_dev *dev, const struct pci_device_id *id)
static void remove (struct pci_dev *dev)
static int __init pci_skel_init (void)
static void __exit pci_skel_exit (void)
module_init (pci_skel_init)
module_exit (pci_skel_exit)
MODULE_LICENSE ("Dual BSD/GPL")
MODULE_AUTHOR ("M.Ulbricht")
MODULE_VERSION ("0.1")
MODULE_DESCRIPTION ("InnoRoute Trustnode driver")
MODULE_DEVICE_TABLE (pci, ids)
Variables
static struct pci_device_id ids []
PCI-Device definition.
struct net_device * INR_NW
static struct pci_driver pci_driver
Detailed Description
main driver Function M.Ulbricht 2015
Definition in file main.c.
Function Documentation
void INR_NWDEV_destroi (void)
destroy nw-device
Definition at line 76 of file main.c.
References INR_LOG_debug(), and INR_NW.
 {
   INR_LOG_debug ("destroy INRNWDEV\n");
   unregister_netdev (INR_NW);
   free_netdev (INR_NW);
 }
static int probe (struct pci_dev * dev, const struct pci_device_id * id) static
init driver function
Definition at line 88 of file main.c.
References INR_CTL_init_ovs(), INR_CTL_init_proc(), INR_init_drv(), INR_LOG_debug(), INR_NWDEV_init(), and INR_STATUS_set().
Referenced by remove().
 {
   printk (KERN_ALERT "moep2\n");
   int result;
   INR_LOG_timelog_init ();  //safe timestamp
   /* Do probing type stuff here.
    * Like calling request_region();
    */
   INR_LOG_debug ("Start load module\n");
   if ((result = pci_enable_device (dev)) < 0) {
     INR_LOG_debug ("device enable fail...\n");
     return result;
   }
   else {
     INR_LOG_debug ("device enabled\n");
     INR_STATUS_set (INR_STATUS_DEVICE);
   }
   //INR_init_drv (dev);           //INIT pci and network
   if (0 == INR_NWDEV_init ())
     INR_STATUS_set (INR_STATUS_NW_enabled);
   INR_init_drv (dev);       //INIT pci and network
   INR_CTL_init_proc (dev);  //init proc fs
   INR_CTL_init_ovs ();      //init openvswitch-dp link
   /*if (skel_get_revision(dev) == 1)
      return -ENODEV; */
   INR_STATUS_set (INR_STATUS_DRV_INIT_done);
   return 0;
 }
static void remove (struct pci_dev * dev) static
driver-end function, called by kernel
Parameters
*dev PCI-device
Definition at line 123 of file main.c.
References ids, INR_CTL_remove_proc(), INR_LOG_debug(), INR_remove_drv(), and probe().
 {
   INR_CTL_remove_proc (dev);
   INR_LOG_debug ("remove Module\n");
   INR_LOG_debug ("Reset Logic\n");
   //msleep (1);
   //writel (0, (gBaseVirt + (4 * 2)));  //reset Logic
   //debug ("Ready-Flag:%i\n", readl ((gBaseVirt + (4 * 3))));
   INR_remove_drv (dev);
   INR_CTL_remove_proc (dev);
 }
Variable Documentation
struct pci_device_id ids[] static
Initial value:
= {
  {PCI_DEVICE (0xAAAA, 0x7024),},
  {0,}
}
PCI-Device definition.
Definition at line 30 of file main.c.
Referenced by remove().
struct net_device* INR_NW
Network device definition
Definition at line 35 of file main.c.
Referenced by INR_NWDEV_destroi(), and INR_NWDEV_init().
struct pci_driver pci_driver static
Initial value:
= {
  .name = "INRTrustnode",
  .id_table = ids,
  .probe = probe,
  .remove = remove,
}
Definition at line 138 of file main.c.